# Generated by Django 4.2.23 on 2025-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='post_params',
            field=models.TextField(blank=True),
        ),
    ]
