# Generated by Django 4.2.23 on 2025-08-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imgs/instituciones')),
            ],
        ),
        migrations.CreateModel(
            name='FotoInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='imgs/instituciones')),
                ('orden', models.IntegerField(default=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='instituciones.institucion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
