# Generated by Django 4.1.4 on 2022-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instituciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="imgs/instituciones"
            ),
        ),
    ]
