# Generated by Django 4.2.3 on 2023-07-20 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("instituciones", "0004_alter_institucion_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FotoInstitucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="imgs/instituciones")),
                ("orden", models.IntegerField(default=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
