# Generated by Django 4.1.4 on 2022-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Celular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_pais", models.CharField(max_length=5)),
                ("codigo_area", models.CharField(max_length=10)),
                ("numero", models.CharField(max_length=20)),
            ],
        ),
    ]
