# Generated by Django 4.2.3 on 2023-07-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                (
                    "persona_id",
                    models.CharField(
                        blank=True,
                        help_text="DNI, Cedula, RUT, etc.",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "email_principal",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "celular_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="celular_principal_de",
                        to="core.celular",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
    ]
