# Generated by Django 4.2.3 on 2023-08-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasdromUserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LI', 'Login'), ('LO', 'Logout'), ('SE', 'Search')], max_length=2)),
                ('generic_text1', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_text2', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_number1', models.IntegerField(blank=True, null=True)),
                ('generic_number2', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasdromUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=20, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_picture_url', models.URLField(blank=True, null=True)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('celular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clasdrom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='clasdromuseraction',
            name='clasdrom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='usuarios.clasdromusuario'),
        ),
    ]
