# Generated by Django 4.2.3 on 2023-07-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aulas", "0001_initial"),
        ("instituciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instituciones.institucion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caracteristicaenaula",
            unique_together={("aula", "caracteristica")},
        ),
    ]
