# Generated by Django 4.1.4 on 2022-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aula",
            name="capacidad_alumnos",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
