# Generated by Django 4.1.4 on 2022-12-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0002_alter_aula_capacidad_alumnos"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aula",
            name="pizarra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aula",
            name="proyector",
            field=models.BooleanField(default=False),
        ),
    ]
