# Generated by Django 4.1.4 on 2022-12-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0003_aula_ac_aula_pizarra_aula_proyector"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FotoAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="imgs/aulas")),
                ("orden", models.IntegerField(default=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="aulas.aula",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
