# Generated by Django 4.1.4 on 2022-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0004_aula_descripcion_fotoaula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoaula",
            name="foto",
            field=models.ImageField(upload_to="media/imgs/aulas"),
        ),
    ]
