# Generated by Django 4.1.4 on 2022-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0005_alter_fotoaula_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoaula",
            name="foto",
            field=models.ImageField(upload_to="imgs/aulas"),
        ),
    ]
