# Generated by Django 4.2.3 on 2023-07-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_caracteristicaaula_remove_aula_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicaaula',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caracteristicaaula',
            name='se_debe_pedir',
            field=models.BooleanField(default=True),
        ),
    ]
