# Generated by Django 4.2.23 on 2025-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='code',
            field=models.CharField(default='NO', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
