# Generated by Django 4.2.23 on 2025-08-17 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_preinscripcion_preinscripcionextras'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
