# Generated by Django 4.2.23 on 2025-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_preinscripcion_created_preinscripcion_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo - Sin contactar'), ('contactado', 'Contactado'), ('interesado', 'Interesado - Respondió positivamente'), ('dudoso', 'Dudoso - Necesita más información'), ('confirmado', 'Confirmado - Listo para inscribirse'), ('inscripto', 'Inscripto - Ya es alumno'), ('no_interesado', 'No interesado'), ('no_responde', 'No responde')], default='nuevo', help_text='Estado actual del seguimiento del lead', max_length=20),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='notas_seguimiento',
            field=models.TextField(blank=True, help_text='Notas sobre las conversaciones y seguimiento del lead', null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='ultimo_contacto',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último contacto con el lead', null=True),
        ),
    ]
